apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      name: sleep
      labels:
        app: sleep
    spec:
      containers:
        - name: sleep
          image: alpine:latest
          command: ["/bin/sh"]
          args:
          - "-c"
          - |-
            for i in 0 1 2 3 4 5 6 7 8 9; do
              for j in 0 1 2 3 4 5 6 7 8 9; do
                echo -n \"${i}${j}: \"
                date
                sleep 1
              done
            done
