apiVersion: v1
kind: Service
metadata:
  name: prometheus
  annotations:
    prometheus.io/scrape: "true"
  labels:
    name: prometheus
spec:
  type: ClusterIP
  ports:
  - name: prometheus-http
    port: 80
    targetPort: 9090
    protocol: TCP
  selector:
    app: prometheus