apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
spec:
  type: NodePort
  ports:
  - name: prometheus-http
    port: 80
    targetPort: 9090
    nodePort: 30280
    protocol: TCP
  selector:
    app: prometheus