apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          args:
            - "-config.file=/etc/prometheus/prometheus.yml"
            - "-storage.local.path=/prometheus"
            - "-web.console.libraries=/etc/prometheus/console_libraries"
            - "-web.console.templates=/etc/prometheus/consoles"
            - "-storage.local.retention=6h"
            - "-storage.local.memory-chunks=500000"
            - "-config.file=/etc/prometheus/prometheus.yml"
          ports:
          - name: web
            containerPort: 9090
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
            - name: prometheus-data
              mountPath: /prometheus
      volumes:
        - name: prometheus-data
          emptyDir: {}
        - name: config-volume
          configMap:
            name: prometheus-config