apiVersion: v1
kind: Service
metadata:
  name: httphostname
  labels:
    app: httphostname
    version: v0.1.3
spec:
  type: NodePort
  sessionAffinity: None
  ports:
  - name: httphostname-http
    port: 80
    targetPort: 80
    nodePort: 30180
    protocol: TCP
  selector:
    app: httphostname
    version: v0.1.2