apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  ports:
  - name: prometheus-http
    port: 80
    targetPort: 3000
    nodePort: 30180
    protocol: TCP
  selector:
    app: grafana