apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: node-exporter
    name: node-exporter
  name: node-exporter
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: scrape
    port: 9100
    protocol: TCP
  selector:
    app: node-exporter
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'false'
  labels:
    app: node-exporter-nodeport
    name: node-exporter-nodeport
  name: node-exporter-nodeport
spec:
  type: NodePort
  # type: clusterIP
  # clusterIP: None
  ports:
  - name: scrape
    port: 9100
    targetPort: 9100
    nodePort: 30980
    protocol: TCP
  selector:
    app: node-exporter
